### ISSUE TITLE
Conflict with Python

### ISSUE THREAD

**Issue by Ambrevar** [nschum/guess-style#2]
Running Emacs 24.3 with the following setup

``` LISP
(autoload 'guess-style-set-variable "guess-style" nil t)
(autoload 'guess-style-guess-variable "guess-style")
(autoload 'guess-style-guess-all "guess-style" nil t)
(setq guess-style-info-mode 1)
(add-hook 'prog-mode-hook 'guess-style-guess-all)
```

yields the following error message when loading python-mode:

```
File mode specification error: (error "Don't know how to make a localized variable an alias")
```

and python-mode will not load, which is fairly annoying.

Replacing the deprecated `python-indent` by `python-indent-offset` in `guess-style-guesser-alist` did the trick for me.

**Comment by pkgw** [comment]
The fix for this bug breaks for emacs 25.1, since the "and" clause evaluates to false since the minor version is less than 3.
